const { chromium } = require('playwright');
const http = require('node:http');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {passReview}=require('./helpers.cjs');
const handler = require('../server');
(async()=>{
  delete process.env.OPENAI_API_KEY;
  const server=http.createServer(handler);
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const base=`http://127.0.0.1:${server.address().port}`;
  const browser=await chromium.launch({headless:true,channel:'chrome'});
  try {
    const page=await browser.newPage({viewport:{width:1365,height:1000}});
    const errors=[]; page.on('pageerror',e=>errors.push(e.message));
    const screenshots=path.resolve(__dirname,'../../output/frag-sls-v1.4.3-qa'); fs.mkdirSync(screenshots,{recursive:true});
    await page.goto(base);
    await page.evaluate(()=>document.fonts.ready);
    await page.screenshot({path:path.join(screenshots,'sia-start-desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.screenshot({path:path.join(screenshots,'sia-start-mobile.png'),fullPage:true});
    await page.setViewportSize({width:1365,height:1000});
    assert.match(await page.title(),/SLS Immobilien/);
    assert.equal(await page.locator('#aiIntro').isVisible(),true);
    assert.equal(await page.locator('#aiAdvice').isVisible(),false);
    await page.getByRole('textbox').fill('Welche festen Bestandteile hat die Verkaufsbegleitung?');
    await page.locator('#ask').click();
    await page.waitForFunction(()=>document.querySelector('#answerOrigin').textContent==='Antwort von: Wissensbasis von SLS Immobilienpartner');
    assert.match(await page.locator('#answerNotice').innerText(),/nicht eingerichtet/);
    assert.ok(await page.locator('#sources strong').count()>0);
    await page.screenshot({path:path.join(screenshots,'wissensbasis-desktop.png'),fullPage:true});
    process.env.OPENAI_API_KEY='test-only-not-a-real-key';
    let calls=0;
    globalThis.fetch=async (url,options)=>{
      calls++; assert.equal(url,'https://api.openai.com/v1/responses');
      const body=JSON.parse(options.body); assert.equal(body.model,'gpt-4.1-mini');
      if(body.text.format.name==='answer_review')return {ok:true,json:async()=>passReview(body)};
      return {ok:true,json:async()=>({status:'completed',output:[{type:'message',role:'assistant',content:[{type:'output_text',text:JSON.stringify({paragraphs:[{kind:'general',text:'Räumen Sie persönliche Dokumente weg und sorgen Sie für freie Flächen.',source_ids:[]},{kind:'company',text:'Die Präsentation wird auf die Immobilie abgestimmt.',source_ids:['presentation-services']}]})}]}]})};
    };
    await page.locator('#ask').click();
    await page.waitForFunction(()=>document.querySelector('#answerOrigin').textContent==='Antwort von: OpenAI');
    assert.equal(await page.locator('#aiAdvice').isVisible(),true);
    assert.equal(await page.locator('#aiAdvice a').first().getAttribute('href'),'tel:+4923697428020');
    assert.equal(await page.locator('#aiAdvice a').last().getAttribute('href'),'mailto:service@sls.de');
    assert.match(await page.locator('#answerParagraphs').innerText(),/Räumen/);
    assert.equal(calls,2); assert.match(await page.locator('#answerParagraphs').innerText(),/\[\d+\]/);
    assert.equal(await page.locator('#sources strong').count(),1);
    const [sourcePage]=await Promise.all([page.context().waitForEvent('page'),page.locator('#sources a').first().click()]);
    await sourcePage.waitForLoadState();assert.match(await sourcePage.locator('body').innerText(),/SLS Immobilien/);await sourcePage.close();
    await page.screenshot({path:path.join(screenshots,'openai-mock-desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await page.locator('#answerCard').scrollIntoViewIfNeeded();
    await page.locator('#answerCard').screenshot({path:path.join(screenshots,'openai-mock-answer-mobile.png')});
    await page.screenshot({path:path.join(screenshots,'openai-mock-mobile.png'),fullPage:true});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    globalThis.fetch=async()=>({ok:false,status:401});
    await page.locator('#ask').click();
    await page.waitForFunction(()=>document.querySelector('#answerOrigin').textContent==='Antwort von: Wissensbasis von SLS Immobilienpartner');
    assert.match(await page.locator('#answerNotice').innerText(),/authentifiziert/);
    assert.equal(await page.locator('#aiAdvice').isVisible(),false);
    await page.route('**/api/ask',route=>route.fulfill({status:502,contentType:'text/html',body:'Bad gateway'}));
    await page.locator('#ask').click();
    await page.waitForFunction(()=>document.querySelector('#answerOrigin').textContent==='Keine Antwort erhalten');
    assert.equal(await page.locator('#aiAdvice').isVisible(),false);
    assert.equal(await page.locator('#sources strong').count(),0);
    assert.equal(await page.locator('.nextStep').isVisible(),false);
    assert.equal(await page.locator('#ask').isEnabled(),true);
    await page.unroute('**/api/ask');
    await page.getByRole('textbox').fill('Was kostet eine Bewertung?');
    await page.locator('#ask').click();
    await page.waitForFunction(()=>document.querySelector('#answerParagraphs').textContent.includes('sind kostenlos und unverbindlich'));
    assert.equal(await page.locator('#limitations').count(),0);
    assert.match(await page.locator('#sources').innerText(),/Vom Auftraggeber bestätigt/);
    globalThis.fetch=async(url,options)=>JSON.parse(options.body).text.format.name==='answer_review'?{ok:true,json:async()=>passReview(JSON.parse(options.body))}:({ok:true,json:async()=>({status:'completed',output:[{type:'message',role:'assistant',content:[{type:'output_text',text:JSON.stringify({paragraphs:[{kind:'company',text:'Drohnenaufnahmen sind je nach Immobilie ohne zusätzliche Leistungskosten enthalten.',source_ids:['presentation-services']},{kind:'company',text:'Die Bonitätsprüfung ist enthalten.',source_ids:['sales-services']}]})}]}]})});
    await page.getByRole('textbox').fill('Was kosten die Drohnenaufnahmen und wird die Finanzierung geprüft?');
    await page.locator('#ask').click();
    await page.waitForFunction(()=>document.querySelector('#answerParagraphs').textContent.includes('Bonitätsprüfung'));
    assert.match(await page.locator('#answerParagraphs').innerText(),/ohne zusätzliche Leistungskosten/);
    assert.equal(await page.locator('#limitations').count(),0);
    assert.equal(await page.locator('#sources a').count(),2);
    assert.equal(await page.locator('#aiAdvice').isVisible(),true);
    assert.match(await page.locator('.badge').innerText(),/1.4.3/);
    assert.match(await page.locator('.answerHead').innerText(),/SIA antwortet/i);
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.locator('#answerCard').screenshot({path:path.join(screenshots,'mixed-answer-mobile.png')});
    globalThis.fetch=async(url,options)=>{
      const body=JSON.parse(options.body);
      if(body.text.format.name==='answer_review')return {ok:true,json:async()=>passReview(body)};
      return {ok:true,json:async()=>require('./helpers.cjs').envelope({paragraphs:[{kind:'expert',text:'Ein Notaranderkonto ist kein automatischer Zahlungsweg. Die Verwahrung setzt insbesondere ein berechtigtes Sicherungsinteresse voraus.',source_ids:['notary-escrow']}]})};
    };
    await page.getByRole('textbox').fill('Wird das Geld nach der Beurkundung auf ein Notaranderkonto eingezahlt?');
    await page.locator('#ask').click();
    await page.waitForFunction(()=>document.querySelector('#answerParagraphs').textContent.includes('kein automatischer Zahlungsweg'));
    assert.equal(await page.locator('#aiAdvice').isVisible(),true);
    assert.equal(await page.locator('#limitations').count(),0);
    assert.match(await page.locator('#sources').innerText(),/Fachgrundlage/);
    const [expertPage]=await Promise.all([page.context().waitForEvent('page'),page.locator('#sources a').first().click()]);
    await expertPage.waitForLoadState();
    assert.ok(await expertPage.locator('a[href="https://www.gesetze-im-internet.de/beurkg/__57.html"]').count());
    await expertPage.close();
    await page.locator('#answerCard').screenshot({path:path.join(screenshots,'expert-answer-mobile.png')});
    globalThis.fetch=async(url,options)=>({ok:true,json:async()=>JSON.parse(options.body).text.format.name==='answer_review'
      ?require('./helpers.cjs').envelope({complete:true,concise:true,paragraphs:[{index:0,supported:false}]})
      :require('./helpers.cjs').envelope({paragraphs:[{kind:'expert',text:'Der Kaufpreis geht immer auf ein Notaranderkonto.',source_ids:['notary-escrow']}]})});
    await page.locator('#ask').click();
    await page.waitForFunction(()=>document.querySelector('#answerOrigin').textContent==='Antwort von: Wissensbasis von SLS Immobilienpartner');
    assert.ok(!(await page.locator('#answerParagraphs').innerText()).includes('geht immer'));
    assert.match(await page.locator('#answerParagraphs').innerText(),/nicht automatisch/);
    assert.equal(await page.locator('#aiAdvice').isVisible(),false);
    assert.deepEqual(errors,[]);
    console.log('Browser PASS: real UI → local API → mock OpenAI → cited answer; missing key, auth fallback, invalid server response, mobile layout, no page errors.');
  } finally { await browser.close(); await new Promise(resolve=>server.close(resolve)); }
})().catch(e=>{console.error(e);process.exitCode=1});
