import locations from './buyer-geodata.json' with {type:'json'};
export const normalise=v=>String(v??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').trim().replace(/\s+/g,' ');
export function distance(a,b){const r=Math.PI/180,dlat=(b.lat-a.lat)*r,dlng=(b.lng-a.lng)*r,x=Math.sin(dlat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dlng/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
const index=new Map();
for(const [zip,city,lat,lng] of locations){for(const key of [zip,normalise(city)]){if(!index.has(key))index.set(key,[]);index.get(key).push({city,lat,lng});}}
export function locate(input){const key=normalise(input),rows=index.get(key);if(!rows?.length)return null;const point={city:rows[0].city,lat:rows.reduce((s,x)=>s+x.lat,0)/rows.length,lng:rows.reduce((s,x)=>s+x.lng,0)/rows.length};if(rows.some(x=>distance(point,x)>30))return null;return point;}
const types={house:['HOUSE'],apartment:['APARTMENT'],multi:['HOUSE','INVESTMENT'],land:['TRADE_SITE'],commercial:['OFFICE','GASTRONOMY','INDUSTRY','STORE','SPECIAL_PURPOSE']};
export const categories={house:['SINGLE_FAMILY_HOUSE','TWO_FAMILY_HOUSE','TERRACE_HOUSE','SEMIDETACHED_HOUSE','BUNGALOW','VILLA'],apartment:['ROOF_STOREY','APARTMENT','GROUND_FLOOR','PENTHOUSE','MAISONETTE'],multi:['MULTI_FAMILY_HOUSE'],land:[],commercial:[]};
export function parseDemand(body){const type=String(body.propertyType||''),area=Number(body.area),rooms=Number(body.rooms||0),price=body.price===''||body.price==null?null:Number(body.price),place=String(body.place||'').trim(),category=String(body.category||'');if(!types[type]||!Number.isFinite(area)||area<=0||area>1e6||!Number.isFinite(rooms)||rooms<0||rooms>1000||(['house','apartment','multi'].includes(type)&&rooms<1)||price!==null&&(!Number.isFinite(price)||price<=0||price>1e9)||place.length>150||category&&!categories[type].includes(category))throw new Error('Bitte prüfen Sie die Angaben zu Ihrer Immobilie.');const point=locate(place);if(!point)throw new Error('Bitte geben Sie eine eindeutige Postleitzahl in NRW oder einen vollständigen Ortsnamen ein.');return {type,area,rooms,price,place,point,category:type==='multi'?'MULTI_FAMILY_HOUSE':category};}
const list=v=>Array.isArray(v)?v:[];
function range(value,from,to){for(const raw of [from,to])if(raw!=null&&raw!==''&&!Number.isFinite(Number(raw)))return false;return !(from!=null&&from!==''&&value<Number(from)||to!=null&&to!==''&&value>Number(to));}
function geographic(profile,point){const lat=profile.lat,lng=profile.lng,radius=Number(profile.radius);if(lat!=null&&lng!=null&&Number.isFinite(Number(lat))&&Number.isFinite(Number(lng))&&Number(lat)>=-90&&Number(lat)<=90&&Number(lng)>=-180&&Number(lng)<=180&&Number.isFinite(radius)&&radius>=0&&distance(point,{lat:Number(lat),lng:Number(lng)})<=radius/1000+20)return true;return list(profile.cities).some(city=>{const p=locate(city);return p&&distance(point,p)<=20;});}
export function countDemand(profiles,criteria){const clients=new Set();for(const p of profiles){if(p.active!==true||p.marketing_type!=='BUY'||!Number.isSafeInteger(Number(p.client_id))||Number(p.client_id)<=0)continue;const rt=list(p.rs_types);if(!rt.length||!rt.some(t=>types[criteria.type].includes(t)))continue;const cats=list(p.rs_categories);if(cats.length&&(!criteria.category||!cats.includes(criteria.category)))continue;if(!geographic(p,criteria.point))continue;const field=criteria.type==='land'?'plot_area':criteria.type==='commercial'?'net_floor_space':'living_space';if(!range(criteria.area,p[field],p[field+'_to']))continue;if(criteria.rooms&&!range(criteria.rooms,p.number_of_rooms,p.number_of_rooms_to))continue;if(criteria.price!==null&&!range(criteria.price,p.price,p.price_to))continue;clients.add(String(p.client_id));}return {count:clients.size,priceChecked:criteria.price!==null,location:criteria.point.city,radiusKm:20};}
