import {createHmac} from 'node:crypto';
import {parseDemand,countDemand,demandInventory} from '../lib/buyer-demand.mjs';
let snapshot=null,inflight=null;const limits=new Map();
async function profiles(key){
  if(snapshot&&snapshot.until>Date.now())return snapshot;if(inflight)return inflight;
  inflight=(async()=>{
    const deadline=Date.now()+48000,all=[],seen=new Set();
    async function page(number){if(Date.now()>deadline)throw new Error('read_timeout');const r=await fetch(`https://api.propstack.de/v1/saved_queries?per=100&page=${number}`,{headers:{'X-API-KEY':key},signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error('read_http_'+r.status);const data=await r.json();const rows=Array.isArray(data)?data:data.data;if(!Array.isArray(rows))throw new Error('unexpected_list_schema');return {rows,total:Number(data.meta?.total_count)};}
    function append(rows){for(const row of rows){if(!row.id||seen.has(String(row.id)))throw new Error('pagination_repeated');seen.add(String(row.id));all.push(row);}}
    const first=await page(1);append(first.rows);
    if(Number.isFinite(first.total)){
      if(first.total>25000)throw new Error('pagination_limit');if(first.total>0&&!first.rows.length)throw new Error('empty_first_page');
      const size=first.rows.length||100,pages=Math.ceil(first.total/size);
      for(let start=2;start<=pages;start+=6){const group=await Promise.all(Array.from({length:Math.min(6,pages-start+1)},(_,i)=>page(start+i)));for(const p of group)append(p.rows);}
      if(all.length!==first.total)throw new Error('pagination_incomplete');
    }else{
      for(let n=2,last=first.rows.length;last===100;n++){if(n>250)throw new Error('pagination_limit');const p=await page(n);append(p.rows);last=p.rows.length;}
    }
    const distribution={};for(const label of ['BUY','RENT','UNSET','OTHER']){const selected=all.filter(p=>{const type=String(p.marketing_type??'').trim();return label==='UNSET'?!type:label==='OTHER'?type&&!['BUY','RENT'].includes(type):type===label;});const clients=rows=>new Set(rows.filter(p=>Number.isSafeInteger(Number(p.client_id))&&Number(p.client_id)>0).map(p=>String(p.client_id))).size;distribution[label]={profiles:selected.length,activeProfiles:selected.filter(p=>p.active===true).length,clients:clients(selected),activeClients:clients(selected.filter(p=>p.active===true))};}const activeAll=all.filter(p=>p.active===true),unique=rows=>new Set(rows.filter(p=>Number.isSafeInteger(Number(p.client_id))&&Number(p.client_id)>0).map(p=>String(p.client_id))).size;
    console.info('SLS buyer demand distribution',JSON.stringify({profiles:all.length,clients:unique(all),activeClients:unique(activeAll),activeBuyOrUnsetClients:unique(activeAll.filter(p=>p.marketing_type==='BUY'||!String(p.marketing_type??'').trim())),distribution}));
    snapshot={rows:all,checkedAt:new Date().toISOString(),until:Date.now()+300000};return snapshot;
  })().finally(()=>{inflight=null;});return inflight;
}
export default async function handler(req,res){res.setHeader('Cache-Control','private, no-store');res.setHeader('X-Robots-Tag','noindex, nofollow');if(req.method!=='GET')return res.status(405).json({error:'Methode nicht erlaubt.'});const host=String(req.headers?.host||'').toLowerCase();if(!['sls.de','www.sls.de','sls-website-eight.vercel.app'].includes(host)&&!(process.env.VERCEL_ENV==='preview'&&/^[a-z0-9-]+\.vercel\.app$/.test(host))&&!(process.env.NODE_ENV!=='production'&&/^localhost(?::\d+)?$/.test(host)))return res.status(403).json({error:'Anfrage nicht erlaubt.'});const key=process.env.PROPSTACK_SEARCH_PROFILE_API_KEY||process.env.PROPSTACK_API_KEY;if(!key)return res.status(503).json({error:'Der automatische Nachfragecheck ist gerade nicht verfügbar. Wir prüfen die Nachfrage gerne persönlich für Sie.'});const summary=req.query?.summary==='1';let criteria;try{if(!summary)criteria=parseDemand(req.query||{});}catch(error){return res.status(400).json({error:error.message});}const now=Date.now();for(const [k,v] of limits)if(v.until<now)limits.delete(k);const ip=String(req.headers?.['x-vercel-forwarded-for']||req.headers?.['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0],hash=createHmac('sha256',key).update(ip).digest('hex'),limit=limits.get(hash)||{count:0,until:now+900000};limit.count++;limits.set(hash,limit);if(limit.count>30)return res.status(429).json({error:'Bitte versuchen Sie den Nachfragecheck später erneut.'});try{const data=await profiles(key),analysedClients=demandInventory(data.rows);if(summary)return res.status(200).json({analysedClients,checkedAt:data.checkedAt});const result=countDemand(data.rows,criteria);return res.status(200).json({...result,analysedClients,checkedAt:data.checkedAt,method:'Aktive Suchprofile für Kauf oder ohne Kauf-/Mietangabe mit Suchorten oder Suchradien im 20-km-Umfeld. Ausdrückliche Mietgesuche sind ausgeschlossen. Ortsmittelpunkte sind Näherungen. Personen werden einmal gezählt; weitere Wünsche und konkrete Lage werden persönlich geprüft.'});}catch(error){console.warn('SLS buyer demand unavailable',error.name==='TimeoutError'?'read_timeout':error.message); return res.status(503).json({error:'Der automatische Nachfragecheck ist gerade nicht verfügbar. Wir prüfen die Nachfrage gerne persönlich für Sie.'});}}
