import test from 'node:test';import assert from 'node:assert/strict';import {locate,parseDemand,countDemand,distance,demandInventory} from '../lib/buyer-demand.mjs';
const criteria=parseDemand({propertyType:'house',category:'SINGLE_FAMILY_HOUSE',place:'Dorsten',area:'120',rooms:'4',price:'350000'});
const base={id:1,client_id:10,active:true,marketing_type:'BUY',rs_types:['HOUSE'],rs_categories:['SINGLE_FAMILY_HOUSE'],cities:['Dorsten'],living_space:100,living_space_to:140,number_of_rooms:3,price_to:400000};
test('Only active, buying, geographically and numerically matching people count once',()=>{const profiles=[base,{...base,id:2},{...base,id:3,client_id:11,cities:['Düsseldorf']},{...base,id:4,client_id:12,active:false},{...base,id:5,client_id:13,marketing_type:'RENT'},{...base,id:6,client_id:14,rs_types:['APARTMENT']},{...base,id:7,client_id:15,price_to:300000},{...base,id:8,client_id:16,living_space:130},{...base,id:9,client_id:17,number_of_rooms:5},{...base,id:10,client_id:18,rs_categories:['VILLA']}];assert.equal(countDemand(profiles,criteria).count,1);});
test('Search circles intersect requested 5-km area; zero coordinates never mean missing values',()=>{const p={...base,cities:[],lat:criteria.point.lat,lng:criteria.point.lng,radius:1000};assert.equal(countDemand([p],criteria).count,1);assert.equal(countDemand([{...p,lat:0,lng:0}],criteria).count,0);assert.equal(countDemand([{...p,lat:null,lng:null}],criteria).count,0);});
test('Unknown or ambiguous places and invalid values are rejected',()=>{for(const change of [{place:'Not-a-place'},{area:'NaN'},{price:'-20'},{propertyType:'fake'},{category:'INVENTED'},{rooms:0}])assert.throws(()=>parseDemand({...criteria,propertyType:'house',...change}));assert.equal(locate('40213').city,'Düsseldorf');assert.ok(distance(locate('Dorsten'),locate('Düsseldorf'))>20);});
test('Unspecified price and category do not restrict matching',()=>{assert.equal(countDemand([{...base,price_to:100000}],{...criteria,price:null}).count,1);assert.equal(countDemand([base],{...criteria,category:''}).count,1);assert.equal(countDemand([{...base,rs_categories:[]}],{...criteria,category:''}).count,1);});
test('Land uses land area, not living area; zero matches are real',()=>{const c=parseDemand({propertyType:'land',place:'Dorsten',area:500});assert.equal(countDemand([{...base,rs_types:['TRADE_SITE'],rs_categories:[],plot_area:400,plot_area_to:600,living_space:999}],c).count,1);assert.equal(countDemand([],c).count,0);});

import {handler} from '../api/buyer-demand.js';
test('Public demand endpoint returns aggregate only; failed complete reads never return a partial count',async()=>{const originalFetch=globalThis.fetch,originalKey=process.env.PROPSTACK_API_KEY;process.env.PROPSTACK_API_KEY='test-key';let writes=0;globalThis.fetch=async(url,options)=>{if(options.method&&options.method!=='GET')writes++;const n=Number(new URL(url).searchParams.get('page'));const rows=n===1?Array.from({length:100},(_,i)=>({...base,id:i+1,client_id:i+1,email:'private@example.test',note:'private'})):[{...base,id:101,client_id:101}];return {ok:true,json:async()=>({data:rows,meta:{total_count:101}})};};let result;const res={setHeader(){},status(code){this.code=code;return this;},json(data){result={code:this.code,data};return this;}};try{await handler({method:'GET',headers:{host:'localhost'},query:{propertyType:'house',category:'SINGLE_FAMILY_HOUSE',place:'Dorsten',area:'120',rooms:'4',price:'350000'}},res);assert.equal(result.code,200);assert.equal(result.data.count,101);assert.equal(result.data.analysedClients,101);await handler({method:'GET',headers:{host:'localhost'},query:{summary:'1'}},res);assert.deepEqual(Object.keys(result.data).sort(),['analysedClients','checkedAt']);assert.equal(result.data.analysedClients,101);assert.equal(writes,0);assert.equal(JSON.stringify(result).includes('private'),false);assert.equal(Object.hasOwn(result.data,'profiles'),false);const {handler:fresh}=await import('../api/buyer-demand.js?failure');globalThis.fetch=async()=>({ok:false,status:403});await fresh({method:'GET',headers:{host:'localhost'},query:{propertyType:'house',place:'Dorsten',area:'120',rooms:'4'}},res);assert.equal(result.code,503);assert.equal(Object.hasOwn(result.data,'count'),false);}finally{globalThis.fetch=originalFetch;if(originalKey===undefined)delete process.env.PROPSTACK_API_KEY;else process.env.PROPSTACK_API_KEY=originalKey;}});

test('Open category includes every matching house category and is never narrower than a selected category',()=>{const profiles=[base,{...base,id:2,client_id:11,rs_categories:['VILLA']},{...base,id:3,client_id:12,rs_categories:['TERRACE_HOUSE']},{...base,id:4,client_id:13,rs_types:['APARTMENT'],rs_categories:['APARTMENT']}];assert.equal(countDemand(profiles,{...criteria,category:''}).count,3);assert.equal(countDemand(profiles,criteria).count,1);assert.equal(countDemand(profiles,{...criteria,category:'VILLA'}).count,1);});

test('Inventory counts only active buying people once, across all regions and categories',()=>{assert.equal(demandInventory([base,{...base,id:2},{...base,id:3,client_id:11,cities:['Düsseldorf']},{...base,id:4,client_id:12,active:false},{...base,id:5,client_id:13,marketing_type:'RENT'},{...base,id:6,client_id:null}]),2);});

test('Active purchase and unspecified marketing types match; rent and inactive profiles never count',()=>{const profiles=[base,...[null,'','   ',undefined].map((type,i)=>({...base,id:i+2,client_id:i+11,marketing_type:type})),{...base,id:6,client_id:20,marketing_type:'RENT'},{...base,id:7,client_id:21,marketing_type:'OTHER'},{...base,id:8,client_id:22,marketing_type:null,active:false},{...base,id:9,marketing_type:null}];assert.equal(demandInventory(profiles),5);assert.equal(countDemand(profiles,criteria).count,5);assert.equal(countDemand([{...base,marketing_type:null,price_to:100000}],criteria).count,0);assert.equal(countDemand([{...base,marketing_type:null,rs_types:['APARTMENT']}],criteria).count,0);});

test('Five kilometre geographic boundary applies to both search cities and circles',()=>{const c={...criteria,point:locate('Recklinghausen')};assert.ok(distance(c.point,locate('Marl'))>5);assert.equal(countDemand([{...base,cities:['Recklinghausen']}],c).count,1);assert.equal(countDemand([{...base,cities:['Marl']}],c).count,0);const p={...base,cities:[],lat:c.point.lat+7/111.195,lng:c.point.lng};assert.equal(countDemand([{...p,radius:1000}],c).count,0);assert.equal(countDemand([{...p,radius:3000}],c).count,1);assert.equal(countDemand([],c).radiusKm,5);});
