import test from 'node:test';
import assert from 'node:assert/strict';
import {withFormSecurity,rateScript,claimScript,finishScript,recoverRejectedScript,securityStore} from '../lib/form-security.mjs';
import {verifyReportEmail,consumeVerificationScript} from '../lib/email-verification.mjs';
function memoryRedis(){const values=new Map(),calls=[];let down=false;return {values,calls,setDown:v=>down=v,fetch:async(url,init)=>{calls.push(JSON.parse(init.body));if(down)return {ok:false};const args=JSON.parse(init.body);let result;const get=k=>values.get(k),set=(k,v)=>values.set(k,v);
 if(args[0]==='SET'){set(args[1],args[2]);result='OK';}
 else if(args[0]==='EVAL'){
  const script=args[1],n=Number(args[2]),keys=args.slice(3,3+n),v=args.slice(3+n);
  if(script===rateScript){result=Number(get(keys[0])||0)+1;set(keys[0],result);}
  else if(script===claimScript){if(get(keys[0]))result=['existing',get(keys[0])];else if(get(keys[1])&&get(keys[1])!==v[0])result=['changed',''];else if(get(keys[2]))result=['busy',''];else{set(keys[0],'{"pending":true}');set(keys[1],v[0]);set(keys[2],v[0]);result=['claimed',''];}}
  else if(script===finishScript){if(get(keys[1])===v[0])values.delete(keys[1]);if(v[1]==='release'){values.delete(keys[0]);values.delete(keys[2]);}else set(keys[0],v[1]);result=1;}
  else if(script===recoverRejectedScript){if(get(keys[3]))result=0;else{set(keys[3],'done');if(get(keys[0])!=='{"pending":true}')result=0;else{values.delete(keys[0]);if(get(keys[1])===v[0])values.delete(keys[1]);if(get(keys[2])&&JSON.parse(get(keys[2])).request===v[0].slice(0,12))values.delete(keys[2]);result=1;}}}
  else if(script===consumeVerificationScript){result=get(keys[0])===v[0]?1:0;if(result)values.delete(keys[0]);}
  else throw Error('Unexpected script');
 }else throw Error('Unexpected command');return {ok:true,json:async()=>({result})};}};}
async function fixture(run){const envNames=['NODE_ENV','VERCEL_ENV','KV_REST_API_URL','KV_REST_API_TOKEN','UPSTASH_REDIS_REST_URL','UPSTASH_REDIS_REST_TOKEN'],before=envNames.map(k=>process.env[k]),oldFetch=global.fetch;Object.assign(process.env,{NODE_ENV:'production',VERCEL_ENV:'production',KV_REST_API_URL:'https://redis.example',KV_REST_API_TOKEN:'synthetic-only'});delete process.env.UPSTASH_REDIS_REST_URL;delete process.env.UPSTASH_REDIS_REST_TOKEN;const db=memoryRedis();global.fetch=db.fetch;
 const request=async(handler,method='POST',body={},extra={})=>{const res={headers:{},setHeader(k,v){this.headers[k]=v;},status(code){this.code=code;return this;},json(body){this.body=body;return this;}};await handler({method,headers:{host:'sls-website-eight.vercel.app',origin:'https://sls-website-eight.vercel.app','content-type':'application/json','x-vercel-forwarded-for':'192.0.2.1',...extra},query:method==='GET'?{formSecurity:'1'}:{},body},res);return res;};
 try{await run({db,request});}finally{global.fetch=oldFetch;envNames.forEach((k,i)=>before[i]===undefined?delete process.env[k]:process.env[k]=before[i]);}}
test('missing or failed shared store rejects before writes',()=>fixture(async({db,request})=>{let writes=0;const h=withFormSecurity('test',async(req,res)=>{writes++;res.status(200).json({ok:true});});db.setDown(true);assert.equal((await request(h,'GET')).code,503);assert.equal(writes,0);delete process.env.KV_REST_API_TOKEN;assert.equal((await request(h,'POST',{})).code,503);assert.equal(writes,0);}));
test('foreign origin, forged forwarded host, missing or tampered token never write',()=>fixture(async({request})=>{let writes=0;const h=withFormSecurity('test',async(req,res)=>{writes++;res.status(200).json({ok:true});});const ready=await request(h,'GET');const body={email:'test@example.org',securityToken:ready.body.securityToken};assert.equal((await request(h,'POST',body,{origin:'https://other.example'})).code,403);assert.equal((await request(h,'POST',body,{host:'other.example','x-forwarded-host':'sls-website-eight.vercel.app'})).code,403);assert.equal((await request(h,'POST',{...body,securityToken:'tampered'})).code,400);assert.equal((await request(h,'POST',{email:body.email})).code,400);assert.equal(writes,0);}));
test('new instances and new tokens replay success without a second write and cache no CRM IDs',()=>fixture(async({request,db})=>{let writes=0;const business=async(req,res)=>{writes++;res.status(200).json({ok:true,contactId:123});};const first=withFormSecurity('test',business),second=withFormSecurity('test',business);const token=(await request(first,'GET')).body.securityToken;assert.deepEqual((await request(first,'POST',{email:'a@example.org',securityToken:token})).body,{ok:true});const newToken=(await request(second,'GET')).body.securityToken;assert.equal((await request(second,'POST',{email:'a@example.org',securityToken:newToken})).code,200);assert.equal(writes,1);assert.ok([...db.values.keys()].every(k=>!k.includes('a@example.org')&&!k.includes('192.0.2.1')));assert.ok([...db.values.values()].every(v=>!String(v).includes('contactId')));}));
test('parallel instances serialize same recipient and prevent simultaneous writes',()=>fixture(async({request})=>{let resolve,writes=0;const wait=new Promise(r=>resolve=r),h=withFormSecurity('test',async(req,res)=>{writes++;await wait;res.status(200).json({ok:true});});const token=(await request(h,'GET')).body.securityToken;const body={email:'a@example.org',securityToken:token};const first=request(h,'POST',body);await new Promise(r=>setImmediate(r));const second=await request(h,'POST',body);assert.equal(second.code,409);assert.equal(writes,1);resolve();assert.equal((await first).code,200);}));
test('uncertain write stays blocked after restart and across new tokens',()=>fixture(async({request})=>{let writes=0;const business=async(req,res)=>{writes++;res.status(502).json({error:'uncertain'});};const h=withFormSecurity('test',business),token=(await request(h,'GET')).body.securityToken;assert.equal((await request(h,'POST',{email:'a@example.org',securityToken:token})).code,502);const restarted=withFormSecurity('test',business),newToken=(await request(restarted,'GET')).body.securityToken;assert.equal((await request(restarted,'POST',{email:'a@example.org',securityToken:newToken})).code,409);assert.equal(writes,1);}));
test('limits apply centrally and failure does not bypass them',()=>fixture(async({request})=>{let writes=0;const h=withFormSecurity('test',async(req,res)=>{writes++;res.status(200).json({ok:true});},{postLimit:2});for(let i=0;i<3;i++){const token=(await request(h,'GET')).body.securityToken;assert.equal((await request(h,'POST',{email:'a@example.org',message:String(i),securityToken:token})).code,i<2?200:429);}assert.equal(writes,2);}));
test('confirmation code is report-bound, recipient-bound and consumed once',()=>fixture(async({db})=>{let sentCode;const contact={email:'a@example.org',firstName:'Anna',lastName:'Muster',phone:''},body={report:{phases:[],contradictions:[]}};const challenge=await verifyReportEmail(body,contact,async(to,code)=>{assert.equal(to,contact.email);sentCode=code;});assert.equal(challenge.status,'email_confirmation_required');assert.ok([...db.values.values()].every(v=>!String(v).includes(sentCode)));await assert.rejects(verifyReportEmail({...body,verificationRef:challenge.verificationRef,verificationCode:sentCode},{...contact,email:'b@example.org'},()=>{}));await assert.rejects(verifyReportEmail({...body,report:{phases:[{}]},verificationRef:challenge.verificationRef,verificationCode:sentCode},contact,()=>{}));assert.equal(await verifyReportEmail({...body,verificationRef:challenge.verificationRef,verificationCode:sentCode},contact,()=>{}),null);await assert.rejects(verifyReportEmail({...body,verificationRef:challenge.verificationRef,verificationCode:sentCode},contact,()=>{}));}));
test('verified rejected-request recovery applies once and preserves new uncertain writes',()=>fixture(async({request})=>{
 const email='a@example.org',fp=securityStore().hash('test:'+JSON.stringify({email}));let writes=0;
 const business=async(req,res)=>{writes++;res.status(502).json({error:'uncertain'});};
 const original=withFormSecurity('test',business);let token=(await request(original,'GET')).body.securityToken;
 assert.equal((await request(original,'POST',{email,securityToken:token})).code,502);
 const recovered=withFormSecurity('test',business,{rejectedRequestPrefixes:[fp.slice(0,12)],recoveryUntil:Date.now()+60000});
 token=(await request(recovered,'GET')).body.securityToken;assert.equal((await request(recovered,'POST',{email,securityToken:token})).code,502);assert.equal(writes,2);
 token=(await request(recovered,'GET')).body.securityToken;assert.equal((await request(recovered,'POST',{email,securityToken:token})).code,409);assert.equal(writes,2);
}));
test('recovery does not release unknown requests or completed results',()=>fixture(async({request})=>{
 let writes=0;const business=async(req,res)=>{writes++;res.status(200).json({ok:true});};const original=withFormSecurity('test',business);let token=(await request(original,'GET')).body.securityToken;
 assert.equal((await request(original,'POST',{email:'a@example.org',securityToken:token})).code,200);
 const fp=securityStore().hash('test:'+JSON.stringify({email:'a@example.org'})),recovered=withFormSecurity('test',business,{rejectedRequestPrefixes:[fp.slice(0,12)],recoveryUntil:Date.now()+60000});token=(await request(recovered,'GET')).body.securityToken;
 assert.equal((await request(recovered,'POST',{email:'a@example.org',securityToken:token})).code,200);assert.equal(writes,1);
 const uncertain=withFormSecurity('other',async(req,res)=>{res.status(502).json({error:'uncertain'});});token=(await request(uncertain,'GET')).body.securityToken;assert.equal((await request(uncertain,'POST',{email:'b@example.org',securityToken:token})).code,502);
 const notKnown=withFormSecurity('other',business,{rejectedRequestPrefixes:[fp.slice(0,12)],recoveryUntil:Date.now()+60000});token=(await request(notKnown,'GET')).body.securityToken;assert.equal((await request(notKnown,'POST',{email:'b@example.org',securityToken:token})).code,409);
}));
