import test from 'node:test';
import assert from 'node:assert/strict';
import handler from '../api/security-monitor.js';
async function fixture(run){
 const keys=['CRON_SECRET','VERCEL_ENV','KV_REST_API_URL','KV_REST_API_TOKEN','UPSTASH_REDIS_REST_URL','UPSTASH_REDIS_REST_TOKEN','SECURITY_ALERT_EMAIL','MS_GRAPH_TENANT_ID','MS_GRAPH_CLIENT_ID','MS_GRAPH_CLIENT_SECRET'],before=keys.map(k=>process.env[k]),oldFetch=global.fetch;
 Object.assign(process.env,{CRON_SECRET:'synthetic-cron',VERCEL_ENV:'production',KV_REST_API_URL:'https://redis.example',KV_REST_API_TOKEN:'synthetic-redis',MS_GRAPH_TENANT_ID:'synthetic-tenant',MS_GRAPH_CLIENT_ID:'synthetic-id',MS_GRAPH_CLIENT_SECRET:'synthetic-secret'});delete process.env.UPSTASH_REDIS_REST_URL;delete process.env.UPSTASH_REDIS_REST_TOKEN;delete process.env.SECURITY_ALERT_EMAIL;
 const state={down:false,review:null,siaStatus:401,locked:false,sent:[],calls:[]};
 global.fetch=async(url,init={})=>{state.calls.push(String(url));if(String(url).includes('redis.example')){if(state.down)throw Error('synthetic outage');const args=JSON.parse(init.body);let result;if(args[0]==='PING')result='PONG';else if(args[0]==='GET')result=state.review;else if(args[0]==='SET'){result=state.locked?null:'OK';state.locked=true;}else throw Error('unexpected Redis command');return {ok:true,json:async()=>({result})};}if(String(url).includes('frag-sls.vercel.app'))return {status:state.siaStatus};if(String(url).includes('login.microsoftonline.com'))return {ok:true,json:async()=>({access_token:'synthetic-token'})};if(String(url).includes('graph.microsoft.com')){state.sent.push(JSON.parse(init.body));return {ok:true,status:202};}throw Error('unexpected URL');};
 const request=async(auth='Bearer synthetic-cron',method='GET')=>{const res={setHeader(){},status(n){this.code=n;return this;},json(body){this.body=body;return this;}};await handler({method,headers:{authorization:auth}},res);return res;};
 try{await run({state,request});}finally{global.fetch=oldFetch;keys.forEach((k,i)=>before[i]===undefined?delete process.env[k]:process.env[k]=before[i]);}
}
test('monitor refuses unauthenticated checks before accessing services',()=>fixture(async({state,request})=>{assert.equal((await request('Bearer wrong')).code,401);assert.equal((await request('', 'POST')).code,405);assert.equal(state.calls.length,0);delete process.env.CRON_SECRET;assert.equal((await request('Bearer undefined')).code,401);}));
test('monitor remains quiet when storage and upstream authorization pass',()=>fixture(async({state,request})=>{process.env.SECURITY_ALERT_EMAIL='synthetic@example.org';const r=await request();assert.equal(r.code,200);assert.equal(state.sent.length,0);}));
test('failed storage creates dashboard warning without an unspecified recipient',()=>fixture(async({state,request})=>{state.down=true;const r=await request();assert.equal(r.code,503);assert.deepEqual(r.body.issues,['central_store_unavailable']);assert.equal(r.body.notification,'dashboard');assert.equal(state.sent.length,0);}));
test('uncertain writes notify only configured recipient and coalesce concurrent checks',()=>fixture(async({state,request})=>{process.env.SECURITY_ALERT_EMAIL='synthetic@example.org';state.review=JSON.stringify({scope:'contact',request:'synthetic',at:Date.now()});const [a,b]=await Promise.all([request(),request()]);assert.equal(a.code,503);assert.equal(b.code,503);assert.equal(state.sent.length,1);assert.equal(state.sent[0].message.toRecipients[0].emailAddress.address,'synthetic@example.org');assert.equal(state.sent[0].message.attachments,undefined);assert.match(state.sent[0].message.body.content,/form_write_needs_review/);assert.equal(state.sent[0].saveToSentItems,true);}));
test('monitor detects publicly callable upstream and never runs in preview',()=>fixture(async({state,request})=>{state.siaStatus=200;assert.deepEqual((await request()).body.issues,['sia_auth_check_failed']);state.calls.length=0;process.env.VERCEL_ENV='preview';assert.equal((await request()).body.skipped,'preview');assert.equal(state.calls.length,0);}));
